### ISSUE TITLE
[Question] Will this work with many users?

### ISSUE THREAD

**Issue by lyz-code** [fe80Grau/ytdlp2STRM#11]
Hi, thanks for the plugin, I was wondering if each jellyfin user would be able to set their own channels to follow, or if all channels would be available for all users

Thanks

**Comment by fe80Grau** [comment]
Hi, is not possible at the moment because each cahnnel has a unique folder (library) to save strm files. I'm working with c# in order to deploy this as real Jellyfin plugin with config interface. I put your request in my to do list.
