### ISSUE TITLE
Can we get this as a docker image?

### ISSUE THREAD

**Issue by hhalsaif** [fe80Grau/ytdlp2STRM#12]
Hello!
This project looks real cool and seems to do exactly what I want it (mainly streaming Youtube and Twitch), but I don’t want to run it as a direct service can this be packaged as a docker. Thanks.

**Comment by fe80Grau** [comment]
Iep!
In addition to some features, I've added a Dockerfile and the instructions in the README. Try it and tell me if everything goes well.
