### ISSUE TITLE
systemd file doesnt work

### ISSUE THREAD

**Issue by Amateur-God** [fe80Grau/ytdlp2STRM#17]
systemd file exits with the following error

```● ytdlp2strm.service - ytdlp2STRM Service
     Loaded: loaded (/etc/systemd/system/ytdlp2strm.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2023-11-06 07:04:02 GMT; 1s ago
    Process: 228880 ExecStart=/usr/bin/python3 /opt/ytdlp2STRM/main.py (code=exited, status=1/FAILURE)
   Main PID: 228880 (code=exited, status=1/FAILURE)
        CPU: 352ms
```
could be with how you starting it i recommend specifying a user and using the following exec start

```ExecStart=/bin/bash -c cd /opt/ytdlp2STRM/ && python3 main.py ```

**Comment by fe80Grau** [comment]
can you paste here the full output. (you can check this with systemctl status ytdl2strm.service)
Tell me your OS version.
If you set this to root, you don't need to specify the user in the .service file

**Comment by Amateur-God** [comment]
> can you paste here the full output. (you can check this with systemctl status ytdl2strm.service) Tell me your OS version. If you configure ytdlp2strm as root, you don't need to specify the user in the .service file

it could be that then as i specifically don't run anything as root, not even my own code,

**Comment by fe80Grau** [comment]
with chown youruser:yourgroup -R /opt/ytdl2strm may be works
