### ISSUE TITLE
yt-dlp error with cruncyroll

### ISSUE THREAD

**Issue by Amateur-God** [fe80Grau/ytdlp2STRM#18]
yt-dlp: error: playlist start "0" must be positive

**Comment by fe80Grau** [comment]
I think it was fixed with the latest commit.

**Comment by Amateur-God** [comment]
this seems to of fixed it however I'm now constantly getting Cloudflare blocks, is it possible to proxy this through a proxy like flaresolverr which i use for prowlarr? 

ive provided new cookies like 4 times and everytime it gets blocked by cloudflare, im running this on a headless linux server

**Comment by fe80Grau** [comment]
have you checked this? https://github.com/yt-dlp/yt-dlp/issues/7442#issuecomment-1685036245
You must set exactly the current user agent of the browser that is refreshing the cookie. Many people comment that it works without reloading the Crunchyroll page in the current browser to update the cookie, but in my case I need to open the Crunchyroll episode with Firefox browser in the background and automatically close after a minute, this cron (scheduled task on Windows) every 15

**Comment by pixelroll** [comment]
what needs to be done concretely... please
