### ISSUE TITLE
movies block updates on Crunchyroll

### ISSUE THREAD

**Issue by pixelroll** [fe80Grau/ytdlp2STRM#23]
example:
for jujutsu kaisen, the film jujutsu kaisen 0 is in season 10 (ytdlp2strm detects it as 44 oddly enough) , so the last episode is marked further back than season 2, which is currently airing and therefore no longer updates.

en image :
![image](https://github.com/fe80Grau/ytdlp2STRM/assets/32129359/d8d21a0b-226b-4a29-9829-2f25fa114321)
last_episode.txt : 347 while the real last episode is 43

**Comment by fe80Grau** [comment]
I added a condition to ignore items in playlist with episode_number == 0, try with the last commit.
