### ISSUE TITLE
Option to place live stream in different season

### ISSUE THREAD

**Issue by dcflachs** [fe80Grau/ytdlp2STRM#24]
It would be nice to have an option to place the live stream .strm file in a subfolder separate from the other available streams. Particularly i would like a subfolder named some variant of s0, season-0, etc. That would make jellyfin place the live stream in a separate season than the others making it easier to find for some channels.

**Comment by dcflachs** [comment]
The goal of this request is to get the live stream to appear in a different season than the other on demand videos to make it more easily accessible. Perhaps there is a better way to do this than subfolders, like something with the nfo file.

**Comment by fe80Grau** [comment]
I'm in holidays far away of my home when i come back in few days i wikl check all pensing issues.

**Comment by fe80Grau** [comment]
Try the last commit in main, now the twitch videos have been stored separately in live and videos folder.

**Comment by dcflachs** [comment]
This is great thank you!
There is a small bug though, the live strm files are not being deleted when the stream ends. I think this will fix it https://github.com/fe80Grau/ytdlp2STRM/pull/25
