### ISSUE TITLE
Docker Image On Docker Hub

### ISSUE THREAD

**Issue by 2IkHLHB** [fe80Grau/ytdlp2STRM#26]
I'm running Docker on a NAS that doesn't allow me to option to build Docker images. If it's not too much asking, please have option of hosting Docker images on Docker Hub.

**Comment by fe80Grau** [comment]
Hola, aquí tienes
https://hub.docker.com/r/fe80grau/ytdlp2strm/tags

*Para la imagen Docker es necesaria una variable de entorno llamada DOCKER_PORT, que por defecto trae el valor 5005, este es el puerto que debe funcionar en el host y por defecto el servicio dentro del contendor se expone por el 5000. Si deseas cambiar el puerto del host también deberás indicarlo como variable de entorno en el momento de ejecutar el contenedor para que reemplace el por defecto en el DockerFile.

Recuerda indicar un volumen para el directorio /media de ytdlp2strm para guardar de forma permanente los strm en el host. 

Si tienes problemas con esto avísame
