### ISSUE TITLE
Youtube plugin - audio only option?

### ISSUE THREAD

**Issue by INPoppoRTUNE** [fe80Grau/ytdlp2STRM#30]
Hi man,
first of all let me say: amazing work, I’m truly loving it so far.

Now I’d like to ask if there is or will ever be implemented a way to generate audio only streams: I know yt-dlp support this option, so it would be a nice to have.

Thanks for your time.

**Comment by fe80Grau** [comment]
I have updated the code a little so that YouTube urls or ids can have the extractaudio- prefix, this way the URL format will no longer be best, but bestaudio, redirecting to the url of the best available audio channel.

Soon I will update the README.md to make it clear and I will implement this same thing for Twitch because I find it interesting.

You can try it in the last commit, tell me if it works for you

**Comment by INPoppoRTUNE** [comment]
> I have updated the code a little so that YouTube urls or ids can have the extractaudio- prefix, this way the URL format will no longer be best, but bestaudio, redirecting to the url of the best available audio channel.

So the url should be `http://url:port/youtube/direct/extractaudio-youtubeid` or `http://url:port/extractaudio-youtube/direct/youtubeid`?

> You can try it in the last commit, tell me if it works for you

You didn't push the commit to the [Dockerhub](https://hub.docker.com/r/fe80grau/ytdlp2strm/tags) and I'm using docker compose, so I'll be unable to test it until you push it.

**Comment by fe80Grau** [comment]
Sorry, you are right about the Dockerhub image... I just did the push.
About  extractaudio- prefix, this is for channel_list.json 
`
[
"extractaudio-https://www.youtube.com/@channel"
]
`

The url sintax used as content in the strm files to extract only audio is: http://url:port/youtube/direct/youtubeid-audio

**Comment by INPoppoRTUNE** [comment]
Thanks for the push, I updated it.

> About extractaudio- prefix, this is for channel_list.json `[ "extractaudio-https://www.youtube.com/@channel" ]`

I’m interested in using it with `keyword-something --dateafter now-1day`, how should I add the extract audio option in this case? `—extractaudio`?

> The url sintax used as content in the strm files to extract only audio is: http://url:port/youtube/direct/youtubeid-audio

I think something is not working properly as:
`http://url:port/youtube/direct/krIus0i9xn8&si=oN0iz21XSgZevrwZ`returned [this link](https://rr5---sn-hpa7znsz.googlevideo.com/videoplayback?expire=1706977105&ei=8RK-Zc7ZHu2g6dsPs7qlsA4&ip=2.235.184.211&id=o-ANHQEft_ruSqglmov_2IR8B4B2jCnZzqaYXkwYcqLtH0&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=10216038&ratebypass=yes&dur=182.230&lmt=1577676291396055&fexp=24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAM4eMdMIf01hxcjxU3AZQ4KldukUEnComFQcx5c9Y4ZgAiAAhQPfM2lUjKLGn9n-vl2-3XB2haK2y5F-TjGeB7cmSw%3D%3D&redirect_counter=1&cm2rm=sn-45nufxc-ugos7l&req_id=8c673c459637a3ee&cms_redirect=yes&cmsv=e&ipbypass=yes&mh=PY&mm=29&mn=sn-hpa7znsz&ms=rdu&mt=1706955194&mv=m&mvi=5&pl=21&lsparams=ipbypass,mh,mm,mn,ms,mv,mvi,pl&lsig=AAO5W4owRQIhAKdASbEx5Q0JVNBsS1u3UfsKU7NcntNwRANnO3imrNbKAiBCYQ48M042-wbFhVJWnKNxZkDis6Hnrr8FZMArSbPppg%3D%3D)
and 
`http://url:port/youtube/direct/krIus0i9xn8&si=oN0iz21XSgZevrwZ-audio`returned [this link](https://rr2---sn-45nufxc-ugos.googlevideo.com/videoplayback?expire=1706977158&ei=JhO-ZcLfCY-L6dsP-cuXmAY&ip=2.235.184.211&id=o-AA5CE7PwmlcCuMyntBnV1Yn4ih6ELkyzaWAJur95nZq4&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=PY&mm=31%2C29&mn=sn-45nufxc-ugos%2Csn-hpa7znsz&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=1911250&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=10216038&ratebypass=yes&dur=182.230&lmt=1577676291396055&mt=1706955198&fvip=5&fexp=24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAOvYzHSkO_pnz0qXcxdY4CBWx0fTXM8imPrPf0xI6_98AiB3qhFtXfwdPkjs_ll5nFLIZmAcgw8t7vzDew_xxeTBEg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIhAN9FITVQcwJFHr_qADDIU5Zrkhh9a3VeuqUSwW0c4m4cAiAEm2CRiZ4FFJ7I3mK10p_IzFVjuR0yMnibx5ETnTN9hg%3D%3D)
Where both links are carrying video data.

**Comment by fe80Grau** [comment]
with keyword- prefix you can set extractaudio- prefix too. Example in channel_list.json
`
[ 'extractaudio-keyword-kase o']
`

In your example the url is very strange. The correct video id is: krIus0i9xn8 
By doing the last commit and restarting the service it should work.

In my case this URL is working fine:
http://url:port/youtube/direct/krIus0i9xn8-audio

**Comment by INPoppoRTUNE** [comment]
> In my case this URL is working fine: http://url:port/youtube/direct/krIus0i9xn8-audio

I’m not able to reproduce that link:
![IMG_1482](https://github.com/fe80Grau/ytdlp2STRM/assets/23138929/004e438c-1bb0-4751-a714-cf283578fef6)

it’s working fine without the `-audio` selector.

**Comment by fe80Grau** [comment]
can you share your channel_list.json? 
I think you are wrong with -audio sufix (generated by the script as content in strm, you don't need to edit these automatically generated strm files) and extractaudio- prefix, needed in channel_list json

**Comment by INPoppoRTUNE** [comment]
> can you share your channel_list.json? I think you are wrong with -audio sufix (generated by the script as content in strm, you don't need to edit these automatically generated strm files) and extractaudio- prefix, needed in channel_list json

I’m currently experimenting just with URLS directly, not through the channel_list.json.
I’m doing so using a [Shortcut](https://support.apple.com/en-gb/guide/shortcuts/welcome/ios) that, given a Youtube URL, it auto trim the video id and append it to `http://url:port/youtube/direct/`:
![IMG_1483](https://github.com/fe80Grau/ytdlp2STRM/assets/23138929/66c4480e-1010-4808-94c2-5fb413d2c7bb)then it automatically opens it in the default browser.

This is working perfectly for the video output, but returns the previous error if I manually add the `-audio` suffix at the end of the same generated URL.
I tried also to run the `-audio` URL using different browsers on different OS, all of them are returning the same error.

**Comment by fe80Grau** [comment]
Mmmm can you check /opt/ytdlp2STRM/plugins/youtube/youtube.py lines 656 to 675?  
You should see this
![image](https://github.com/fe80Grau/ytdlp2STRM/assets/6680464/b154d9dd-b538-44e4-813b-f5113290ae8c)

And if you can see your Docker terminal you can check the command executed when you are trying to start a video with -audio sufix.

![image](https://github.com/fe80Grau/ytdlp2STRM/assets/6680464/eb82251a-87c5-4589-9a9f-d034dd338f46)

**Comment by INPoppoRTUNE** [comment]
> Mmmm can you check /opt/ytdlp2STRM/plugins/youtube/youtube.py lines 656 to 675? You should see this 

Nope, here's my output:
![immagine](https://github.com/fe80Grau/ytdlp2STRM/assets/23138929/2787f434-9478-4ab7-ab1f-43ed8ca73e62)

> And if you can see your Docker terminal you can check the command executed when you are trying to start a video with -audio sufix.

Given this video URL: https://www.youtube.com/watch?v=krsBRQbOPQ4 I get as output:

- `url:port/youtube/direct/krsBRQbOPQ4` → `deviceurl - - [04/Feb/2024 11:44:18] "GET /youtube/direct/krsBRQbOPQ4 HTTP/1.1" 301 -`

- `url:port/youtube/direct/krsBRQbOPQ4-audio` → `deviceurl - - [04/Feb/2024 11:45:50] "GET /youtube/direct/krsBRQbOPQ4-audio HTTP/1.1" 301 -`

But no player is loaded and Firefox is returning an error similar to [this one](https://support.mozilla.org/en-US/questions/1259070), but with (http) instead of (javascript).
`-audio` URL is not able to play on VLC nor MPV also.

**Comment by fe80Grau** [comment]
are you sure you are using latest image ? 
https://hub.docker.com/layers/fe80grau/ytdlp2strm/latest/images/sha256:92cd01bd59dce27d1affe209a38508a38bc6205c0ef61cc445cf78043eec02e1

My output using latest image:
![image](https://github.com/fe80Grau/ytdlp2STRM/assets/6680464/159d28ba-4849-49ac-ab86-43fb61184c8b)

**Comment by INPoppoRTUNE** [comment]
> are you sure you are using latest image ? https://hub.docker.com/layers/fe80grau/ytdlp2strm/latest/images/sha256:92cd01bd59dce27d1affe209a38508a38bc6205c0ef61cc445cf78043eec02e1

My server updated this morning from version `20b86d594907` to `adb9a85a6136`, but I'm now seeing that there is a new release `92cd01bd59dc`.
I now tried to manually force an update: the ID of the image remained the same `sha256:adb9a85a61366625a3826cf7db0bc025fab6949e7ae9d6c4f9ab80f714223cdd `, but now the output of the `sed` command is different (?)
```bash
sed -n '656, 675p' /opt/ytdlp2STRM/plugins/youtube/youtube.py 
def direct(youtube_id): #Sponsorblock doesn't work in this mode
    s_youtube_id = youtube_id.split('-audio')[0]

    command = [
        'yt-dlp', 
        '-f', 'best',
        '--no-warnings',
        '--get-url', 
        s_youtube_id
    ]
    Youtube().set_proxy(command)
    if '-audio' in youtube_id:
        command[2] = 'bestaudio'

    print(' '.join(command))
    youtube_url = w.worker(command).output()
    return redirect(
        youtube_url, 
        code=301
    )
 ```
I'm really confused, but now it's working.
May this depend from the fact that I destroy and rebuilt the `ytdlp2strm-data` volume, allowing the container to fully update?

**Comment by fe80Grau** [comment]
https://stackoverflow.com/questions/38441159/docker-named-volume-not-updating
maybe this can explain it

**Comment by INPoppoRTUNE** [comment]
> In my case this URL is working fine: http://url:port/youtube/direct/krIus0i9xn8-audio

Audio only option seems to be broken.
http://url:port/youtube/direct/krIus0i9xn8-audio return error
http://url:port/youtube/direct/krIus0i9xn8 is working fine

**Comment by fe80Grau** [comment]
@INPoppoRTUNE , It's working correctly for me. If you pull the last commit I have activated some prints to see the yt-dlp commands that are executed, please try and comment here on the output of your terminal after trying to play a strm with -audio

**Comment by harleckinz** [comment]
Any update? I ran into the same issue. url-audio just stuck in Redirecting while without -audio it gets the video.
