### ISSUE TITLE
can this service stream audio only from youtube

### ISSUE THREAD

**Issue by fanyangto** [fe80Grau/ytdlp2STRM#33]
This awesome plugin deserves a lot more attention. 

Many want to listen to youtube's audio stream only. Can this service stream audio only ? 
Many other solutions require downloading files and use ffmpeg to generate and save an audio file. 
I see your self-hosted service as a great solution to youtube audio listening without saving audio files. Could you comment on audio streaming ? 

Now that I have it installed and up running. I can see from the web interface, lots of powerful features. But it's not clear what I need to do in jellyfin to utilize this youtube plugin ? Can you add in your MD file what the user needs to do ? 

For example, in your sample youtube channels, you have

- keyword-kase o
- extractaudio-https://www.youtube.com/@luisitocomunica

Is the keyword-kbase for any keyword search ? 
what is extractaudio doing ? Does it extract audio of all files from the channel ?

**Comment by fe80Grau** [comment]
Thank you @fanyangto , yep the keyword- is the prefix to get videos from youtube search , you just need to add a new element in your youtube list with this prefix and the keyword you want seach. For example if you want to search for "football", add a new item like "keyword-football".

And the extractaudio- prefix means that the strm files only play the audio from all the videos in the channel. For example, if you want to stream only the audio of @LiveMusicRadio channel, add a new element like "extractaudio-https://www.youtube.com/@LiveMusicRadio"

**Comment by fanyangto** [comment]
Thanks a lot. 

If youtube uses the direct method, no video/audio is actually downloaded. Instead, jelly fin will use strm to play the stream through the youtube plugin?

**Comment by fe80Grau** [comment]
Try leaving the quantity field empty and in the every field indicate hour (singular).
I'm using schedule library, take a look for more information https://schedule.readthedocs.io/en/stable/
*used in clases/cron/cron.py 
```
call_constructor = "schedule.every({}).{}.at('{}').do(main_cli, {})".format(
    cron['qty'],
    cron['every'],
    cron['at'],
    cron['do']
)
```
