### ISSUE TITLE
youtube .strm files not playable in jellyfin

### ISSUE THREAD

**Issue by fanyangto** [fe80Grau/ytdlp2STRM#35]
I used the docker image and it seems to work fine. After the youtube channels are generated and .strm files are there. I copy them to jellyfin lib folder and did a lib scan. 

Jellyfin appears to show these media files, but none are playable. When I play it, it complained about it's not a playable format or recognized format. 

What did I miss ?

**Comment by fe80Grau** [comment]
What port are you working with in Docker? Is the DOCKER_PORT variable set to the same value as the Docker host port??? 
Open with notepad any strm to check if the url has the same DOCKER_PORT and try to play your strm files with vlc

**Comment by p-rintz** [comment]
I am using port 5000 inside docker, as well as outside.
URL looks like the following (for example):
```http://10.0.0.22:5000/youtube/bridge/b73xG1HlFhY```

URL does not work in Jellyfin, Firefox, Vivaldi or VLC.

VLC and Vivaldi does not give any error.
Firefox and Jellyfin complain about not being compatible.


```This client isn't compatible with the media and the server isn't sending a compatible media format.```

**Comment by p-rintz** [comment]
Can confirm it works!

Thank you!
