### ISSUE TITLE
Add timezone field to configure in cron

### ISSUE THREAD

**Issue by Sarin-jacob** [fe80Grau/ytdlp2STRM#39]
I have used the docker method and configured the channels and configs. But  when i went into the output directory(bind to /media) there were no files. So I added a  cron job to run it for the first time. After trying a few more times. I ran the cli.py from the container, this time the strm files were properly created.
I had tried to look for cron logs but couldn't find it. Can u tell me how to switch the logging to debug? Should i edit the main.py?
Thanks in advance..

**Comment by Sarin-jacob** [comment]
I think its fixed now.. I had restarted the container once.. And the job seem to start(as shown in logs) 10 mins after  the specied time. Is there anyway to change the time zone?

**Comment by fe80Grau** [comment]
Added, pull the last commit and updated ./config/crons.json file with time zone (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones). If you still the time zone to blank, it gets the machine's default time zone
