### ISSUE TITLE
Crunchyroll broke again ?

### ISSUE THREAD

**Issue by Floflo10** [fe80Grau/ytdlp2STRM#45]
Hi ! 
Look like crunchyroll broke something again because yesterday no new episode was downloaded. Didn't get an error message, just a list of `Preparing channel` and that's it.
I looked around a bit and found https://github.com/yt-dlp/yt-dlp/issues/9994 and this https://github.com/yt-dlp/yt-dlp/pull/10005
Maybe we need to update the version (and the docker image) ? :)

Have a nice day ! :)

**Comment by fe80Grau** [comment]
Yes, I think that was fixed with last night's nightly build https://github.com/yt-dlp/yt-dlp-nightly-builds/releases
`yt-dlp --update-to nightly`

**Comment by fe80Grau** [comment]
https://github.com/fe80Grau/ytdlp2STRM/issues/47

**Comment by Floflo10** [comment]
Oh sorry I forgot ton anwser with my job. 
I couldn't update with your suggestion but I managed to success using Pip. 
All fixed ! Thanks a lot for your awesome work !
