### ISSUE TITLE
Friendly ping to update dockerhub image

### ISSUE THREAD

**Issue by DarkYamik** [fe80Grau/ytdlp2STRM#49]
Hello!

Just a friendly ping to post the updated image with ffmpeg nightly to the dockerhub image!

Thats all! Thanks a lot for your project, loving it so far 🥇

**Comment by fe80Grau** [comment]
Hi!
ty for remember it! here it is https://hub.docker.com/layers/fe80grau/ytdlp2strm/latest/images/sha256:3825d701dad550991986df5f1b5a947b1dfd6ce515b289625441bed9a0218450?uuid=D4737E7E-CEA0-4F2B-8F89-8E3B4A7A840D
