### ISSUE TITLE
Guide maybe? lol

### ISSUE THREAD

**Issue by DEV-MalletteS** [fe80Grau/ytdlp2STRM#51]
Hey bro, huge Jellyfin fan here annd your git repo is exciting! But I need a little bit of help. It's installed andn everything but I need a bit of help on what to input in Crunchyroll, Jellyfin base URL, API, etc. I know you can get an API from the dashboard and I know how to get the user ID, but I nneed more details, sort of like, is there a certain plugin to install? How is it going to appear in my medias or display?

Please assist bro!

**Comment by fe80Grau** [comment]
It is not necessary to install any plugin in Jellyfin, simply add the directory where you are generating the strms to your library, everything will appear in your Jellyfin and it is capable of playing the strms natively.

Then the configuration for the integration between the Crunchyroll plugin for ytdlp2STRM is very basic,

jellyfin_base_url: the address of your Jellyfin, if you have it locally then something like http://192.168.1.X:8096, it also accepts domains, in my case I have a no-ip one with type http://xxxx.ddns. net:8096

jellyfin_user_id and jellyfin_api_key you already mentioned that you know the values, just put them.

There is another related parameter in the general configuration and it is ytdlp2strm_temp_file_duration, here you specify in seconds how long you want the temporary files that are necessarily downloaded to last. Default is 86400 seconds (24 hours)

I hope that with this and the README.md I have resolved your doubts.

**Comment by DEV-MalletteS** [comment]
Thank you, where exactly do I add those files, I've seen them on my disk drive under C:\Media\Twitch. I was wondering where to add them in Jellyfin, as a movie? A show? Live TV?


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fe80Grau** [comment]
Ieeeeep.
You can manage the strm folder in plugin settings with strm_output_folder option.

In Jellyfin I use TV Show.
