### ISSUE TITLE
ERROR [youtube] p7zmysRHeyw This video is available to this channel's members

### ISSUE THREAD

**Issue by HolographicX** [fe80Grau/ytdlp2STRM#54]
When importing from the channel https://www.youtube.com/@bigthink, the script creates the following folder:
```
@bigthink [ERROR [youtube] p7zmysRHeyw This video is available to this channel'\''s members on level Think Even Bigger (or any higher level). Join this channel to get access to members-only content and other exclusive perks.]
```
with no videos in it.

I have tried different youtube_configs, including reducing `days_dateafter` to `1` so it doesn't consider the member only videos at all. Everything results in the same folder with no videos.

Running the docker image from docker hub.

Side note: thank you so much for the awesome project!

**Comment by fe80Grau** [comment]
Check last coomit please, I have rewritten the entire Youtube plugin
