### ISSUE TITLE
Playback Errors

### ISSUE THREAD

**Issue by snppls** [fe80Grau/ytdlp2STRM#55]
Thanks for the great project.

My instance seems to import videos but it won't play anything. I get playback errors every time I try to play something. Any suggestions?

![Screenshot 2024-07-04 171732](https://github.com/fe80Grau/ytdlp2STRM/assets/156883144/a2fa4e70-0ddf-4a9c-b3a8-a2556b05188c)

**Comment by SuperPiggy5000** [comment]
I am getting the same issue as well

**Comment by fe80Grau** [comment]
Can you copy here an example of your channel_list.json?

**Comment by IIIPr0t0typ3III** [comment]
Hey there. I have maybe a similar problem (regarding only YouTube; Twitch works fine):

Everything from the channel_list downloads fine and I get the `.strm` files as well as the `.nfo` files but when I try to open the`.strm` in Jellyfin it loads a little and then tells me
 > ### Playback Error
 > Playback failed due to a fatal player error.

I also tried accessing the link directly in firefox which redirects me to the underlying googlevideo link and results in a HTTP response of 403 (Forbidden) while the page stays blank.
I am not sure if that helps but I thought providing that information doesn't hurt.

If I can help to further debug and fix this just let me know!

 On another note: Thanks for providing and maintaining this cool project!

**Comment by IIIPr0t0typ3III** [comment]
I just found the problem: It is an out of date version of `yt-dlp`
I went into the container via `docker exec -it ytdlp2strm bash` and updated `yt-dlp` to the latest version via `pip install --upgrade yt-dlp --user`. And everything works after that.

A possible general fix might be to just add a cronjob on your host machine that runs the update command once a day (maximum of 24h where the streaming does not work) like:
```
0   0   *   *   *   docker exec ytdlp2strm pip install --upgrade yt-dlp --user
```

**Comment by Druidblack** [comment]
I tried to open those links that are created in a file that can be accessed by opening a link from the program. Google informs me that there is suspicious activity from my address and does not allow me to open the video stream. Could this be giving an error in jf?

**Comment by Druidblack** [comment]
I tried broadcasting from twitch, I get the same error about a fatal playback error.

**Comment by fe80Grau** [comment]
Hi, sorry for the delay in getting back to you. I'm very busy with work. Let's try to solve your issue.

First of all, I see that in the first screenshot you sent, there's an error in detecting the name of the channel.. [ERROR unsupported URL...]

First, run the following command in your terminal and let's see its output:
``` 
yt-dlp https://www.youtube.com/@TheoVon --compat-options no-youtube-unavailable-videos --compat-options no-youtube-channel-redirect --print "%(channel)s" --restrict-filenames --playlist-items 1 
``` 

Then, try to get a direct URL and see what happens:
```
yt-dlp -f best https://www.youtube.com/watch?v=tLFvJ7OvVP4 --get-url
```

This should return a URL. Try to play this URL with VLC or directly in a browser.

With this, I want to check whether the issue you're experiencing is with yt-dlp or due to some blockage from YouTube.

**Comment by Druidblack** [comment]
The error with determining the channel name is due to the fact that in the settings file (example) you suggest specifying the full link to the channel (stream). Because of this, the program adds an extra / when scanning . There is a mistake because of this .if you do it in the program as shown in the screenshot, then there is no such error.

 But it also raises the question why does the program add /video at the end of the channel request line?

![Безымянный](https://github.com/user-attachments/assets/f467addb-773d-4b10-b843-3e12ac07a0c5)

**Comment by Druidblack** [comment]
![Безымянный](https://github.com/user-attachments/assets/c5057c92-e9d6-4a48-81b8-60ce67e50ced)

**Comment by Druidblack** [comment]
![Безымянный](https://github.com/user-attachments/assets/c23dff20-8f8d-4f25-94a6-eb2092ac9e4a)
That's all I did after the update yt-dlp (pip install --upgrade yt-dlp --user)

**Comment by Druidblack** [comment]
Does the program not delete old files after creating new ones? She created a lot of files for me.
![Бе121212зымянный](https://github.com/user-attachments/assets/e851d302-63c3-43d7-b12e-92b69e310417)

**Comment by Druidblack** [comment]
I have now started the broadcast that the program generated. And why is there no sound through vlc?
![укуку](https://github.com/user-attachments/assets/bfdec3ac-04c3-48e8-81e6-cd8fb729ca87)

**Comment by Druidblack** [comment]
jf still throws a fatal playback error

**Comment by Druidblack** [comment]
When watching broadcasts, is there a need to enable hardware acceleration in Jf?

**Comment by fe80Grau** [comment]
Point by point:
- I am working correctly with the full URL. /videos is added to avoid shorts. Anyway I fixed the double slash in the URL // when rendering
![image](https://github.com/user-attachments/assets/5236f4cb-5e61-4b60-a7cd-a5a392937947)

- To remove the old strm, edit ./config/config.json and change the value of ytdlp2strm_keep_old_strm to False

- On all my strm files, including the channel tested here @TheoVon, it works for me with audio and video via vlc.

- And no, hardware acceleration is not necessary in JF.

Honestly, with all the problems you are experiencing I think it must be related to the blocking by YouTube. How many channels have you declared in channel_list.json? And what is your value for videos_limit in ./plugins/youtube/config.json?

**Comment by Druidblack** [comment]
I admit, I may have had problems with the sound.
I tried to make links to two streams. Today I will try to add more channels and streams. Youtube blocking works for me at the router level. I'm not the only one with this problem.

**Comment by Druidblack** [comment]
![Безымянный](https://github.com/user-attachments/assets/a7bda7fd-ddf5-408d-bc59-e45435e51fb8)
Apparently you haven't updated the docker image yet.

**Comment by fe80Grau** [comment]
Check last coomit please, I have rewritten the entire Youtube plugin
