### ISSUE TITLE
Add ARM/aarch64 compatible image on Docker hub

### ISSUE THREAD

**Issue by jsspen** [fe80Grau/ytdlp2STRM#56]
I was trying to deploy via docker-compose (in Portainer) on a Raspberry Pi and despite the stack building successfully and the showing as "running" the GUI never becomes accessible. Looking at the logs revealed the problem: `exec /usr/local/bin/python: exec format error`. It seems the image in Docker Hub is for amd64/x86_64 only. I'm ignorant on the difficulty involved in creating a new image or making the current multi-architecture, but if it's not too much trouble I'd love if this were something that could be done!

**Comment by fe80Grau** [comment]
Here, https://hub.docker.com/r/fe80grau/ytdlp2strm/tags
