### ISSUE TITLE
Limited on 480p

### ISSUE THREAD

**Issue by metasystem** [fe80Grau/ytdlp2STRM#57]
It's in title, not the same issue as "higher quality" because is significant lower and not depend of the max flow for unificated files avaible...

**Comment by fe80Grau** [comment]
I know, Google changed their enpoints and the only source with the remuxed audio/video is 420p, so the yt-dlp command used to extract said data stream in direct mode is currently its maximum quality, sorry. ..

In bridge mode you can make a real-time remux of video and audio giving the maximum quality, be it 1080p, even 2160p, try it. The BIG drawback is that navigation does not work, that is, you cannot move forward or backward freely.
Lately I have been overworked and I don't have much time to dedicate to this project, but when I can I do my tests and I'm sure that I will finally find the key that will make it work... patience

**Comment by maximushugus** [comment]
@fe80Grau I confirm I'm not able to have above 480p resolution no matter if  I use direct or bridge mode

**Comment by fe80Grau** [comment]
Do you work with the last commit/docker image?

**Comment by maximushugus** [comment]
Yes, latest docker hub image

**Comment by fe80Grau** [comment]
Ok, then play a video, go to ytdlp2strm root folder and paste here the last lines generated in ytdlp2strm.log

**Comment by maximushugus** [comment]
OK, after looking at the logs in fact 100% of youtube videos was had age restrictions.
After downloading my youtube cookie, and adding it to ytdlp2STRM I van play videos at max resolution
Thanks
