### ISSUE TITLE
The program stops

### ISSUE THREAD

**Issue by Druidblack** [fe80Grau/ytdlp2STRM#65]
I specified 4 channels in the program:
@Pluviophile_Lofi/streams
@LofiGirl/streams
@LofiGirl/videos
@settlefm/videos

The program works correctly on the first channel, creates empty folders on the 2nd and 3rd, and does not launch channel 4 at all
![Безымянный](https://github.com/user-attachments/assets/4baca0b0-8083-4c29-82ab-c50ad117bccb)

**Comment by Druidblack** [comment]
Deleted channel 2 and 3. I left only 1 and 4. An empty folder was created for 4, without files.

**Comment by fe80Grau** [comment]
Check last coomit please, I have rewritten the entire Youtube plugin
