### ISSUE TITLE
Error after trying to deploy latest docker image

### ISSUE THREAD

**Issue by skijbal** [fe80Grau/ytdlp2STRM#71]
![IMG_0048](https://github.com/user-attachments/assets/ef0ec85f-8a47-4936-b4bc-0262d517951b)

**Comment by skijbal** [comment]
Current compose file.

---
version: "2.1"
services:
  ytdlp2strm:
      image: fe80grau/ytdlp2strm
      container_name: ytdlp2strm
      environment:
        - AM_I_IN_A_DOCKER_CONTAINER=Yes
        - DOCKER_PORT=5000
      volumes:
        - /media/union/youtube:/media
        - ytdlp2strm-data:/opt/ytdlp2STRM
      ports:
        - 5000:5000
      restart: always

volumes:
  ytdlp2strm-data:

**Comment by fe80Grau** [comment]
Yes, sorry, the Python image is at the wrong version, I updated again with python:3.12.5, please check the latest image again.

**Comment by skijbal** [comment]
Working now!
