### ISSUE TITLE
No nfo files are created for streams

### ISSUE THREAD

**Issue by Druidblack** [fe80Grau/ytdlp2STRM#72]
![nfo](https://github.com/user-attachments/assets/ab3a3614-944b-493c-b8e1-78d1577ce467)
With the new version, nfo files are not created for streams for each video. (files were created in the old version)

**Comment by fe80Grau** [comment]
Yes, sorry, you can check the last commit. I fixed this for the YouTube plugin. An nfo will be created for each video. And I added a new feature: posters, landscapes and thumbnails will be downloaded for Cemby compatibility.

**Comment by Druidblack** [comment]
Can you upgrade the docker container?

**Comment by Druidblack** [comment]
![2222](https://github.com/user-attachments/assets/e415a1e4-6036-4f19-91d5-a15bf4aadd40)
![1111](https://github.com/user-attachments/assets/ddbfad7b-db24-465b-b25f-5448482dcfb5)
Nfo files are being created, but tabulation is broken in them. The description is created without indentation.

**Comment by Druidblack** [comment]
![4444444](https://github.com/user-attachments/assets/274e98c6-3933-41c6-9efe-4f17519c5e78)
![2222333](https://github.com/user-attachments/assets/2ad50024-75c8-4b69-9d3f-f440eac365e3)

**Comment by fe80Grau** [comment]
Check last docker image and tell me

**Comment by Druidblack** [comment]
![22222222](https://github.com/user-attachments/assets/53663480-a069-4f51-98b2-3828c9faf3a3)
![11111](https://github.com/user-attachments/assets/8f4a26f9-cd7c-4725-8c24-4c9d09a96d4c)
It got better. But there are still problems with formatting the text. jf treats the text with a line break as a single line.

**Comment by fe80Grau** [comment]
In my jf it is displayed correctly
![image](https://github.com/user-attachments/assets/428f046e-be11-40cd-b055-c26b155df475)
![image](https://github.com/user-attachments/assets/a11057a7-c0c9-4cf0-abb8-edbe7cdc4e59)

What is your jf version?

**Comment by Druidblack** [comment]
10.9.10
Is the size of your screenshot your desktop resolution?

I have now checked it on different screen resolutions. The text with the description adjusts to the width of the screen. I will give examples below for 1920x1080, 1920x1440 and 3440x1440.

![222222222](https://github.com/user-attachments/assets/73b58e9f-5b01-48c6-b327-3681513364b6)
![11111111](https://github.com/user-attachments/assets/23190501-9f3e-420a-b1b0-3773ae41599f)
![33333333](https://github.com/user-attachments/assets/14eb9957-5268-4361-af4d-755d5a91ec04)
It is probably necessary that the nfo files contain information that each new line should be a new line, and not a single text.

**Comment by fe80Grau** [comment]
Can you try manually editing an nfo by adding the following after the line you want to cut? (Try with one line and if it works for you, I'll add it in the code)
```
&#x0D;&#x0A; 
```

**Comment by Druidblack** [comment]
It didn't help

**Comment by Druidblack** [comment]
Maybe this will help. When making a plug-in for tubearchivist, the author faced the same text formatting problems. (I participated in testing the plugin). And he corrected such a solid text.
https://github.com/tubearchivist/tubearchivist-jf-plugin

**Comment by fe80Grau** [comment]
Thanks, finally with the combination \n<br/> it seems to be displayed correctly in all cases. Check las docker image
