### ISSUE TITLE
I can't reproduce it later

### ISSUE THREAD

**Issue by Druidblack** [fe80Grau/ytdlp2STRM#75]
The topic has already been raised, but I still can't make the video play. I've tried youtube and twitch. A fatal playback error appears.

I tried to run it later in the docker

I get this entry in the logs

> [2024-09-05 18:06:03.061 +03:00] [INF] [92] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i \"http://192.168.1.161:5007/youtube/direct/r4WHxe0OMqg\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
> [2024-09-05 18:06:03.168 +03:00] [WRN] [82] Jellyfin.Plugin.Themerr.ThemerrManager: ThemerrDB entry not found (404): "Гости из прошлого", contribute:
>   "https://github.com/LizardByte/ThemerrDB/issues/new?assignees=&labels=request-theme&template=theme.yml&title=[TV SHOW]:%20%D0%93%D0%BE%D1%81%D1%82%D0%B8%20%D0%B8%D0%B7%20%D0%BF%D1%80%D0%BE%D1%88%D0%BB%D0%BE%D0%B3%D0%BE%20(2020)&database_url=https://www.themoviedb.org/tv/112113"
> [2024-09-05 18:06:08.089 +03:00] [ERR] [119] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Probe Provider"
> MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
>    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
>    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
> [2024-09-05 18:06:08.125 +03:00] [INF] [119] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "admin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2024-09-05 18:06:08.131 +03:00] [INF] [114] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/config/cache/transcodes/e5fb27aa01aafb312bceb52e942ac5bc.m3u8"
> [2024-09-05 18:06:08.146 +03:00] [INF] [114] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
> [2024-09-05 18:06:08.146 +03:00] [INF] [114] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -noautorotate -i \"http://192.168.1.161:5007/youtube/direct/r4WHxe0OMqg\" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename \"88a21d95a54025ffd7b6ee7f2483298c-1.mp4\" -start_number 0 -hls_base_url \"hls/88a21d95a54025ffd7b6ee7f2483298c/\" -hls_segment_filename \"/config/cache/transcodes/88a21d95a54025ffd7b6ee7f2483298c%d.mp4\" -hls_playlist_type event -hls_list_size 0 -y \"/config/cache/transcodes/88a21d95a54025ffd7b6ee7f2483298c.m3u8\""
> [2024-09-05 18:06:13.177 +03:00] [ERR] [114] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 1
> [2024-09-05 18:06:13.266 +03:00] [ERR] [114] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/0ce32044-ee9f-4423-b0ef-e276e93d33f7/live.m3u8".
> MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
>    at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, Guid userId, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
>    at Jellyfin.Api.Controllers.DynamicHlsController.GetLiveHlsStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 enableSubtitlesInManifest)
>    at lambda_method1377(Closure, Object)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
>    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
>    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
>    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
>    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
>    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
>    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
> [2024-09-05 18:06:13.274 +03:00] [INF] [118] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i \"http://192.168.1.161:5007/youtube/direct/r4WHxe0OMqg\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
> [2024-09-05 18:06:18.310 +03:00] [ERR] [118] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in "Probe Provider"
> MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
>    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
>    at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
>    at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
> [2024-09-05 18:06:18.318 +03:00] [INF] [118] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "admin". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2024-09-05 18:06:18.323 +03:00] [INF] [118] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/config/cache/transcodes/88a21d95a54025ffd7b6ee7f2483298c.m3u8"
> [2024-09-05 18:06:18.336 +03:00] [INF] [118] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
> [2024-09-05 18:06:18.336 +03:00] [INF] [118] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -noautorotate -i \"http://192.168.1.161:5007/youtube/direct/r4WHxe0OMqg\" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename \"d288c5d332f296a69c79b4efdc600fd2-1.mp4\" -start_number 0 -hls_base_url \"hls/d288c5d332f296a69c79b4efdc600fd2/\" -hls_segment_filename \"/config/cache/transcodes/d288c5d332f296a69c79b4efdc600fd2%d.mp4\" -hls_playlist_type event -hls_list_size 0 -y \"/config/cache/transcodes/d288c5d332f296a69c79b4efdc600fd2.m3u8\""
> [2024-09-05 18:06:23.373 +03:00] [ERR] [118] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 1
> [2024-09-05 18:06:23.462 +03:00] [ERR] [118] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/0ce32044-ee9f-4423-b0ef-e276e93d33f7/live.m3u8".
> MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
>    at MediaBrowser.MediaEncoding.Transcoding.TranscodeManager.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, Guid userId, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
>    at Jellyfin.Api.Controllers.DynamicHlsController.GetLiveHlsStream(Guid itemId, String container, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 enableSubtitlesInManifest)
>    at lambda_method1377(Closure, Object)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
>    at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
>    at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
>    at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
>    at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
>    at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
>    at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
> [2024-09-05 18:06:23.668 +03:00] [INF] [119] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/config/cache/transcodes/d288c5d332f296a69c79b4efdc600fd2.m3u8"
> [2024-09-05 18:06:25.174 +03:00] [INF] [119] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.9.10" playing "RAINING IN JAPAN ☔ Pluviophile Lofi ☔ Lofi Sleep Music To Make You Enjoy The Rain And Sleep Well 2024-09-05 1205". Stopped at "0" ms

I also tried running emby. I get the same result. I didn't look at the logs.
I tried running the server natively on Debian 11. The video didn't work. 
I started the server on windows. The video didn't work.

I tried running a stream via vlc player on the same windows PC. The video works well.

What else can I do or install to make the video work jf?

**Comment by fe80Grau** [comment]
If you don't have hardware acceleration, can you try enabling it?

**Comment by Druidblack** [comment]
enabling hardware acceleration on the windows server helped. The video runs for a long time, but eventually starts with transcoding.

**Comment by Druidblack** [comment]
Tell me, can the playback be influenced by the fact that my ip address is used in the file that the program generates? If the ip address changes? And another ip address will remain in the file.

**Comment by fe80Grau** [comment]
Thanks for your tests, I'll do some on my side as well. But I doubt the IP address is the consequence. I think it might be something related to ffmpeg used by JF and Emby, these on Windows are not able to detect the container and therefore require recoding.

In any case, it is necessary that the transmission is done through the dynamic urls of ytdlp2strm, since this will redirect in real time to the final manifest (mpd) of yt, in addition these manifests have information of the videos in SD qualities and at the moment JF and Emby do not correctly manage the selection of qualities according to the bandwidth, that is why ytdlp2strm also modifies in real time the mpd to filter only the highest quality of the video/audio streams, here https://github.com/fe80Grau/ytdlp2STRM/pull/59 and here https://github.com/fe80Grau/ytdlp2STRM/commit/479b94cd5b0e42cebe54bef4222858d4fcf9cf2f

**Comment by Druidblack** [comment]
On Linux in docker (with hardware acceleration enabled)  It was not possible to launch it. Fatal playback error.

I tried to turn on android TV from the same server. the broadcast does not start.

**Comment by fe80Grau** [comment]
Check the latest commit / docker image and tell me if the error persists

**Comment by Druidblack** [comment]
The problem does not relate to playback. But I have updated the docker container now and got an error on startup.

`    from plugins.youtube import youtube
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 10, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'
Traceback (most recent call last):
  File "/opt/ytdlp2STRM/main.py", line 10, in <module>
    from clases.cron import cron as cron
  File "/opt/ytdlp2STRM/clases/cron/cron.py", line 3, in <module>
    from cli import main as main_cli
  File "/opt/ytdlp2STRM/cli.py", line 3, in <module>
    import config.plugins as plugins
  File "/opt/ytdlp2STRM/config/plugins.py", line 2, in <module>
    from plugins.youtube import youtube
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 10, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'
Traceback (most recent call last):
  File "/opt/ytdlp2STRM/main.py", line 10, in <module>
    from clases.cron import cron as cron
  File "/opt/ytdlp2STRM/clases/cron/cron.py", line 3, in <module>
    from cli import main as main_cli
  File "/opt/ytdlp2STRM/cli.py", line 3, in <module>
    import config.plugins as plugins
  File "/opt/ytdlp2STRM/config/plugins.py", line 2, in <module>
    from plugins.youtube import youtube
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 10, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'
Traceback (most recent call last):
  File "/opt/ytdlp2STRM/main.py", line 10, in <module>
    from clases.cron import cron as cron
  File "/opt/ytdlp2STRM/clases/cron/cron.py", line 3, in <module>
    from cli import main as main_cli
  File "/opt/ytdlp2STRM/cli.py", line 3, in <module>
    import config.plugins as plugins
  File "/opt/ytdlp2STRM/config/plugins.py", line 2, in <module>
    from plugins.youtube import youtube
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 10, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'
Traceback (most recent call last):
  File "/opt/ytdlp2STRM/main.py", line 10, in <module>
    from clases.cron import cron as cron
  File "/opt/ytdlp2STRM/clases/cron/cron.py", line 3, in <module>
    from cli import main as main_cli
  File "/opt/ytdlp2STRM/cli.py", line 3, in <module>
    import config.plugins as plugins
  File "/opt/ytdlp2STRM/config/plugins.py", line 2, in <module>
    from plugins.youtube import youtube
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 10, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'
Traceback (most recent call last):
  File "/opt/ytdlp2STRM/main.py", line 10, in <module>
    from clases.cron import cron as cron
  File "/opt/ytdlp2STRM/clases/cron/cron.py", line 3, in <module>
    from cli import main as main_cli
  File "/opt/ytdlp2STRM/cli.py", line 3, in <module>
    import config.plugins as plugins
  File "/opt/ytdlp2STRM/config/plugins.py", line 2, in <module>
    from plugins.youtube import youtube
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 10, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'
Traceback (most recent call last):
  File "/opt/ytdlp2STRM/main.py", line 10, in <module>
    from clases.cron import cron as cron
  File "/opt/ytdlp2STRM/clases/cron/cron.py", line 3, in <module>
    from cli import main as main_cli
  File "/opt/ytdlp2STRM/cli.py", line 3, in <module>
    import config.plugins as plugins
  File "/opt/ytdlp2STRM/config/plugins.py", line 2, in <module>
    from plugins.youtube import youtube
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 10, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'
Traceback (most recent call last):
  File "/opt/ytdlp2STRM/main.py", line 10, in <module>
    from clases.cron import cron as cron
  File "/opt/ytdlp2STRM/clases/cron/cron.py", line 3, in <module>
    from cli import main as main_cli
  File "/opt/ytdlp2STRM/cli.py", line 3, in <module>
    import config.plugins as plugins
  File "/opt/ytdlp2STRM/config/plugins.py", line 2, in <module>
    from plugins.youtube import youtube
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 10, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'
Traceback (most recent call last):
  File "/opt/ytdlp2STRM/main.py", line 10, in <module>
    from clases.cron import cron as cron
  File "/opt/ytdlp2STRM/clases/cron/cron.py", line 3, in <module>
    from cli import main as main_cli
  File "/opt/ytdlp2STRM/cli.py", line 3, in <module>
    import config.plugins as plugins
  File "/opt/ytdlp2STRM/config/plugins.py", line 2, in <module>
    from plugins.youtube import youtube
  File "/opt/ytdlp2STRM/plugins/youtube/youtube.py", line 10, in <module>
    from cachetools import TTLCache
ModuleNotFoundError: No module named 'cachetools'`

**Comment by fe80Grau** [comment]
Oops, that library was missing from the requirements, I've already added it, please check again for the latest commit / docker image

**Comment by Druidblack** [comment]
Updated the container. The program works, but running the video stream in the docker container does not work. Fatal error of the player. Hardware acceleration by the graphics card is enabled.

**Comment by fe80Grau** [comment]
what is the scenario
ytdlp2strm - docker container
jf - docker container
???

the error happens with cookies set or without them too? this is important because with cookies when the content is age restricted it will be redirected to a hls route and if the cookies are not set it will be redirected to a mp4 or webm route directly but in SD. It seems to me that the problem is in how jf is managing the hls routes, if so you should not have problems with redirects in SD

it works with vlc on the host right?
have you tried emby in docker container if the same thing happens as jf?

**Comment by Druidblack** [comment]
ytdlp2strm docker container
![3232](https://github.com/user-attachments/assets/43ccf7f0-ab21-4354-a254-bde55367417b)
here are my settings

jf and emby in docker containers
emby installed and added a folder to jf, enabled hardware acceleration

Video works on PC in vlc
![Безымянный](https://github.com/user-attachments/assets/76d77142-bd14-452c-87d1-2b02afacc902)

I checked it in emdy. The videos are working. But not all of them. The part does not start and gives an error. But part of it turns on and works.
![45454545](https://github.com/user-attachments/assets/ae40b86d-2e7f-46be-a6f6-90ec6ba36296)


in jf, the same videos that work in emby give out a fatal player error.

![4545454545454545](https://github.com/user-attachments/assets/52362a2e-f034-4f67-b774-c0290f10d238)

**Comment by fe80Grau** [comment]
The configuration you are showing is not in the correct format

where cookies simply sets the value to cookies 
and where cookie_value sets the value to /media/cookies.txt

Like:

![image](https://github.com/user-attachments/assets/8362b85c-2cbb-4737-bc28-d1b22413fba4)
