### ISSUE TITLE
ytsearch

### ISSUE THREAD

**Issue by newerit** [fe80Grau/ytdlp2STRM#8]
Hallo i am trying implement 
this function on this code, you help me 
#yt-dlp -f 'best' --no-warning --get-url
#yt-dlp -f 'best' ytsearch10:[AO VIVO] --no-warning --get-url 

and create a @channel_user_name folder before search a kayword on my list file

**Comment by fe80Grau** [comment]
Hi! 
I don't understand you, create the folder BEFORE searching for a keyword in the list? what do you want to do exactly?
Get the strm of the videos of a specific search and have the channel folders automatically created and instead of listing a specific channel, put a word to be searched for?

**Comment by newerit** [comment]
Hallo!

what I'm trying to do is:
  "instead" of creating a list of channels in json is to create a list of keywords where I put what I like and the algorithm would create folders with the names of the channels like @simpsons would save the list of videos strm inside and ... it would be beautiful !

**Comment by newerit** [comment]
you can help me?

**Comment by fe80Grau** [comment]
sure @newerit , pull last commit. Only need to put a new item with prefi keyword-_yourkeyword_ in list inside plugins/youtube/channel_list.json, It's easy but you can check this in  plugins/youtube/channel_list.example.json

**Comment by newerit** [comment]
Good ... i am testing...
PS: the twitch tv not load the miniatures and logos os channels

**Comment by fe80Grau** [comment]
Perfect, you'll tell me when you can. I have been looking at the Twitch images, for now I have something that resolves it, but it's difficult due to the formats, I have forced the call directly to the Twitch endpoint because yt-dlp doesn't get the correct thumbnails

**Comment by newerit** [comment]
Hello, good morning.. The ytsearch function is perfect. But I have a problem with datetime.. yt-dlp downloading video with old dates, can I fix this somehow?

**Comment by fe80Grau** [comment]
without error code or explanation of what you want. i can do nothing.

**Comment by fe80Grau** [comment]
fixed
