### ISSUE TITLE
playback on jellyfin android tv and android app fail

### ISSUE THREAD

**Issue by vortex91** [fe80Grau/ytdlp2STRM#9]
playback works on web version of jellyfin and vlc. but integrated players in jellyfin fail.  Is there a setting i can change to get it to work?

**Comment by fe80Grau** [comment]
With android app you can go to . Settings -> Client Settings -> Video player type. Select Web player, i'm working fine with this.
I don't know if android tv app has the same option. Test it.

**Comment by fe80Grau** [comment]
Test and working fine:

Samsung S20 FE . With external player (VLC) 
Fire Stick (Android TV app) . With ExoPlayer
